execution-workflow2

diff --git a/.github/workflows/11-executionflow.yaml b/.github/workflows/11-executionflow.yaml
--- a/.github/workflows/11-executionflow.yaml
+++ b/.github/workflows/11-executionflow.yaml
@@ -26,6 +26,11 @@ jobs:
         steps:
           - name: Job 3 Step
             run: echo "This is Job 3, which runs after Job 1 and Job 2"
+    SleepJob:
+        runs-on: ubuntu-latest
+        steps:
+          - name: Sleep for 10 seconds
+            run: sleep 10
 # This workflow demonstrates execution flow control using job dependencies.
 # Job3 will only run after both Job1 and Job2 have successfully completed.
 # Use 'needs' keyword to define job dependencies.
@@ -35,9 +40,11 @@ jobs:
         steps:
           - name: Job 4 Step
             run: echo "This is Job 4"
+            
           - name: Conditional Step
             if: ${{ !inputs.conditional-trigger }}
-            run: echo "Conditional trigger is true, so this step runs."
+            run: exit 1
+# Job4 contains a conditional step that will fail if the 'conditional-trigger' input is false
     job5:
         runs-on: ubuntu-latest
         needs: job4
